name: 'Get tests results'
description: 'Retrieve another repository test results'
inputs:
  sha: 
    description: 'Commit SHA'
    required: true
  token: 
    description: 'GH secret token'
    required: true
  repo: 
    description: 'Repository'
    required: true
  owner: 
    description: 'Owner'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'